name: Coveralls GitHub Action

on: ["push", "pull_request"]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x

    - name: npm install, npm run test
      run: |
        npm install
        npm run test:unit  

    - name: Coveralls
      uses: coverallsapp/github-action@v2

    # send the coverage report to coveralls.io
    - name: Coveralls Report
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
