name: Coveralls GitHub Action

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Run npm install, npm run test
        continue-on-error: true
        run: |
          npm install
          npx tap run --coverage-report=lcov test/*.test.js

      # send the coverage report to coveralls.io
      - name: Coveralls Report
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: .tap/report/lcov.info

  bump_version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Run commitizen check
        run: |
          pip install --user -U Commitizen
          cz check --rev-range main..HEAD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Print Version
        run: echo "Bumped to version ${{ steps.cz.outputs.version }}"
