name: Main

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run test
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies and run tests
        continue-on-error: true
        run: |
          npm install
          npx tap run --coverage-report=lcov test/*.test.js

      # send the coverage report to coveralls.io
      - name: Coveralls Report
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: .tap/report/lcov.info

  check:
    name: 'Check commits'
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Install comitizen tool and commitizen check
        run: |
          pip install --user -U Commitizen
          cz check --rev-range origin/main..origin/${{ github.head_ref }}
